# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

# Match Android (newArchEnabled=false). New Arch Fabric interop was crashing
# on unrecognized selector while setting props on a legacy native view.
ENV['RCT_NEW_ARCH_ENABLED'] = '0'

platform :ios, min_ios_version_supported
prepare_react_native_project!

# Required by React Native Firebase so FirebaseCore modules resolve
$RNFirebaseAsStaticFramework = true

#flipper_config = ENV['NO_FLIPPER'] == "1" ? FlipperConfiguration.disabled : FlipperConfiguration.enabled

# Default to static frameworks for Firebase; override with USE_FRAMEWORKS=dynamic if needed
linkage = ENV['USE_FRAMEWORKS'] || 'static'
Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
use_frameworks! :linkage => linkage.to_sym

target 'Ott_client' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/..",
    :new_arch_enabled => false
  )

  target 'Ott_clientTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )

    # Xcode 26.x: fmt 11.0.2 consteval fails with Apple Clang.
    # Patch base.h so consteval is disabled (FMT_USE_CONSTEVAL=0).
    fmt_base = File.join(installer.sandbox.root, 'fmt', 'include', 'fmt', 'base.h')
    if File.exist?(fmt_base)
      content = File.read(fmt_base)
      unless content.include?('Xcode 26 workaround')
        patched = content.gsub(
          /^(#elif defined\(__cpp_consteval\)\n#  define FMT_USE_CONSTEVAL) 1/,
          "// Xcode 26 workaround: disable consteval\n\\1 0"
        )
        if patched != content
          File.chmod(0644, fmt_base)
          File.write(fmt_base, patched)
          Pod::UI.puts "Patched fmt base.h for Xcode 26 consteval fix".green
        end
      end
    end

    # Codegen headers with use_frameworks! :static
    generated_ios = File.join(__dir__, 'build', 'generated', 'ios')
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        header_paths = Array(config.build_settings['HEADER_SEARCH_PATHS'] || ['$(inherited)'])
        header_paths << '"$(PODS_ROOT)/../build/generated/ios"'
        if Dir.exist?(generated_ios)
          Dir.children(generated_ios).each do |child|
            next unless File.directory?(File.join(generated_ios, child))
            header_paths << "\"$(PODS_ROOT)/../build/generated/ios/#{child}\""
          end
        end
        config.build_settings['HEADER_SEARCH_PATHS'] = header_paths.uniq
      end
    end
  end
end
